apiVersion: batch/v1
kind: Job
metadata:
  name: codealltag-ner-gelectra-large-flert-sft-ner-grascco
  namespace: ssaha
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: codealltag-ner-gelectra-large-flert-sft-ner-grascco
    spec:
      containers:
        - name: codealltag-ner-gelectra-large-flert-sft-ner-grascco-container
          image: sksdotsauravs/python-nlp-dev-container:ubuntu24.04-python3.12.11-cuda12.8.1-torch2.7.1
          workingDir: /home/ssaha
          resources:
            requests:
              nvidia.com/gpu: "1"
              memory: "32Gi"
              cpu: "16000m"
            limits:
              nvidia.com/gpu: "1"
              memory: "64Gi"
              cpu: "32000m"
          volumeMounts:
            - name: ssaha-pv
              mountPath: /home/ssaha
          env:
            - name: RUN_PYTHON_SCRIPT
              value: "yes"
            - name: PYTHON_SCRIPT_PATH
              value: "/home/ssaha/Projects/redakt-grascco/src/training_scripts/ner/fine_tune_sequence_tagger_with_transformer_model.py"
            - name: FLAIR_CACHE_ROOT
              value: /home/ssaha/.flair
            - name: HF_HOME
              value: /home/ssaha/.cache/huggingface
            - name: MODEL_CHECKPOINTS_ROOT_DIR
              value: /home/ssaha/model-checkpoints
            - name: DATA_DIR
              value: /home/ssaha/data/grascco
            - name: DATA_FOLD_K_VALUE
              value: "1"
            - name: LOG_TO_WANDB
              value: "1"
            - name: USE_PRETRAINED_MODEL
              value: "1"
            - name: PRETRAINED_MODEL_PATH
              value: /home/ssaha/model-checkpoints/codealltag/ner/deepset--gelectra-large-flert/additional-embeddings-none/use-context-64/sample-size-175000/data-fold-1/learning-rate-5e-5/max-epochs-50/mini-batch-size-50/best-model.pt
            - name: PRETRAINED_MODEL_NAME
              value: calgo-lab/codealltag-ner-gelectra-large-flert
            - name: USE_CONTEXT
              value: "1"
            - name: LEARNING_RATE
              value: "5e-5"
            - name: MAX_EPOCHS
              value: "35"
            - name: MINI_BATCH_SIZE
              value: "1"
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb-secret-sksdotsauravs
                  key: wandb_api_key
      restartPolicy: Never
      volumes:
        - name: ssaha-pv
          persistentVolumeClaim:
            claimName: ssaha-pvc
      nodeSelector:
        gpu: a100